on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
permissions:
  # Goaction needs permissions to update pull requests comments and update contents.
  pull-requests: write
  contents: write
jobs:
  goaction:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Update action files
      uses: posener/goaction@v1
